apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: cdnnow-php-dev-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: cdnnow-php-dev-pod
