apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdnnow-php-dev-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdnnow-php-dev-pod
  template:
    metadata:
      name: cdnnow-php-dev-pod
      labels:
        app: cdnnow-php-dev-pod
    spec:
      containers:
        - name: cdnnow-php-dev-container
          image: cdnnow_php:dev
          ports:
            - containerPort: 9000
