apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdnnow-nginx-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: cdnnow_nginx:dev
          ports:
            - containerPort: 80
