version: "2.3"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      php:
        condition: service_healthy
    environment:
      - ENV=development
  php:
    build: ./php
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
