apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdnnow_homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: api
          image: myapp:dev
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DEBUG
              value: "True"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: code
              mountPath: /app
      volumes:
        - name: code
          hostPath:
            path: /app
