apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdnnow-nginx-prod-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdnnow-nginx-prod-pod
  template:
    metadata:
      name: cdnnow-nginx-prod-pod
      labels:
        app: cdnnow-nginx-prod-pod
    spec:
      containers:
        - name: cdnnow-nginx-prod-container
          image: cdnnow_nginx:prod
          ports:
            - containerPort: 80
